### ISSUE TITLE
Live-reload broken with version 6.0.0+

### ISSUE THREAD

**Issue by boris-petrov** [eflexsystems/ember-cli-webfont#4]
Thanks for keeping this up-to-date!

However, version 6.0.0 broke my live-reload. That is, after I change ANY file (for example some `.hbs` file) - a lot of things are pre-compiled and that takes a lot of time - mostly my CSS. That doesn't happen with version 5.0.1. Any ideas? Perhaps [this](https://github.com/eflexsystems/ember-cli-webfont/commit/368b938c341da3599ff9a151410cf9ea3cc02508) commit broke it.

cc @jakesjews

**Comment by jakesjews** [comment]
@boris-petrov try setting the environment variable BROCCOLI_ENABLED_MEMOIZE=true. Its pretty stable and default in embroider and should fix those issues. You can set it in you ember-cli-build.js file as well with process.env.BROCCOLI_ENABLED_MEMOIZE = 'true';

**Comment by boris-petrov** [comment]
That seems to fix the issue, yes. Thanks a lot! Didn't know about that.
